Updated msys2

diff --git a/msys2/usr/bin/checkupdates b/msys2/usr/bin/checkupdates
--- a/msys2/usr/bin/checkupdates
+++ b/msys2/usr/bin/checkupdates
@@ -19,7 +19,7 @@
 #
 
 declare -r myname='checkupdates'
-declare -r myver='5.0.1'
+declare -r myver='1.0.0'
 
 plain() {
 	(( QUIET )) && return
@@ -78,7 +78,7 @@ readonly ALL_OFF BOLD BLUE GREEN RED YELLOW
 
 
 if (( $# > 0 )); then
-	echo "${myname} (pacman) v${myver}"
+	echo "${myname} v${myver}"
 	echo
 	echo "Safely print a list of pending updates"
 	echo
@@ -94,12 +94,17 @@ fi
 
 trap 'rm -f $CHECKUPDATES_DB/db.lck' INT TERM EXIT
 
-DBPath="${DBPath:-/var/lib/pacman/}"
-eval $(awk -F' *= *' '$1 ~ /DBPath/ { print $1 "=" $2 }' /etc/pacman.conf)
+DBPath="$(pacman-conf DBPath)"
+if [[ -z "$DBPath" ]] || [[ ! -d "$DBPath" ]]; then
+	DBPath="/var/lib/pacman/"
+fi
 
 mkdir -p "$CHECKUPDATES_DB"
 ln -s "${DBPath}/local" "$CHECKUPDATES_DB" &> /dev/null
-pacman -Sy --dbpath "$CHECKUPDATES_DB" --logfile /dev/null &> /dev/null
+if ! pacman -Sy --dbpath "$CHECKUPDATES_DB" --logfile /dev/null &> /dev/null; then
+       error 'Cannot fetch updates'
+       exit 1
+fi
 pacman -Qu --dbpath "$CHECKUPDATES_DB" 2> /dev/null | grep -v '\[.*\]'
 
 exit 0
diff --git a/msys2/usr/bin/pacscripts b/msys2/usr/bin/pacscripts
--- a/msys2/usr/bin/pacscripts
+++ b/msys2/usr/bin/pacscripts
@@ -3,7 +3,6 @@
 #   pacscripts : tries to print out the {pre,post}_{install,remove,upgrade}
 #   scripts of a given package
 #
-#   Copyright (c) 2009 Giulio "giulivo" Fidente <giulivo.navigante@gmail.com>
 #   Copyright (c) 2009 Xavier Chantry <shiningxc@gmail.com>
 #   Copyright (c) 2009-2016 Pacman Development Team <pacman-dev@archlinux.org>
 #
@@ -26,19 +25,7 @@ set -o nounset
 set -o errexit
 
 declare -r myname='pacscripts'
-declare -r myver='5.0.1'
-
-conf="/etc/pacman.conf"
-
-if [ ! -r "$conf" ]; then
-	echo "ERROR: unable to read $conf"
-	exit 1
-fi
-
-eval $(awk '/DBPath/ {print $1$2$3}' "$conf")
-eval $(awk '/CacheDir/ {print $1$2$3}' "$conf")
-pac_db="${DBPath:-/var/lib/pacman}/local"
-pac_cache="${CacheDir:-/var/cache/pacman/pkg}"
+declare -r myver='1.0.0'
 
 error() {
 	local mesg=$1; shift
@@ -46,7 +33,7 @@ error() {
 }
 
 usage() {
-	echo "${myname} (pacman) v${myver}"
+	echo "${myname} v${myver}"
 	echo
 	echo "Prints the {pre,post}_{install,remove,upgrade} scripts of a given package."
 	echo
@@ -59,6 +46,15 @@ usage() {
 	echo "Example: ${myname} gconf-editor"
 	echo "Example: ${myname} gconf-editor-3.0.1-3-x86_64.pkg.tar.xz"
 }
+
+
+if ! DBPath="$(pacman-conf DBPath)"; then
+	error "unable to read /etc/pacman.conf"
+	exit 1
+fi
+CacheDir="$(pacman-conf CacheDir)"
+pac_db="${DBPath:-/var/lib/pacman}/local"
+pac_cache="${CacheDir:-/var/cache/pacman/pkg}"
 
 version() {
 	printf "%s %s\n" "$myname" "$myver"
@@ -126,6 +122,6 @@ fi
 
 case "$1" in
 	--help|-h) usage; exit 0 ;;
-	--version|-V) version; exit 0 ;;
+	--version|-v) version; exit 0 ;;
 	*) print_scriptlet $1 ;;
 esac
diff --git a/msys2/usr/bin/updpkgsums b/msys2/usr/bin/updpkgsums
--- a/msys2/usr/bin/updpkgsums
+++ b/msys2/usr/bin/updpkgsums
@@ -20,19 +20,22 @@
 shopt -s extglob
 
 declare -r myname='updpkgsums'
-declare -r myver='5.0.1'
+declare -r myver='1.0.0'
 
 usage() {
-	printf "%s (pacman) v%s\n" "${myname}" "${myver}"
+	printf "%s v%s\n" "${myname}" "${myver}"
 	echo
 	printf "%s will perform an in place update of the checksums in the\n" "${myname}"
 	echo "path specified by [build file], defaulting to PKGBUILD in the current"
 	echo "working directory."
 	echo
-	printf "Usage: %s [build file]\n" "${myname}"
+	printf "Usage: %s [options] [build file]\n" "${myname}"
 	echo
 	echo "    -h, --help        display this help message and exit"
 	echo "    -V, --version     display version information and exit"
+	echo
+	echo "These options can be passed to makepkg:"
+	echo "    -m, --nocolor     disable colorized output messages"
 }
 
 version() {
@@ -45,12 +48,18 @@ die() {
 	exit 1
 }
 
-case $1 in
-	-h|--help) usage; exit ;;
-	-V|--version) version; exit ;;
-esac
+MAKEPKG_OPTS=()
+buildfile='PKGBUILD'
 
-buildfile=${1:-PKGBUILD}
+while (( "$#" )); do
+	case "$1" in
+		-h|--help) usage; exit ;;
+		-m|--nocolor) MAKEPKG_OPTS+=("$1"); shift ;;
+		-V|--version) version; exit ;;
+		*) buildfile="$1"; break 2 ;;
+	esac
+done
+
 if [[ ! -f $buildfile ]]; then
 	die "%s not found or is not a file" "$buildfile"
 fi
@@ -83,7 +92,7 @@ export BUILDDIR=$(mktemp -d  "${TMPDIR:-/tmp}/updpkgsums.XXXXXX")
 newbuildfile=$(mktemp "${TMPDIR:-/tmp}/updpkgsums.XXXXXX")
 
 trap "rm -rf '$BUILDDIR' '$newbuildfile'" EXIT
-newsums=$(MINGW_PACKAGE_PREFIX=mingw-w64-i686 makepkg -g -p "$buildfile") || die 'Failed to generate new checksums'
+newsums=$(MINGW_PACKAGE_PREFIX=mingw-w64-i686 makepkg -g -p "$buildfile" "${MAKEPKG_OPTS[@]}") || die 'Failed to generate new checksums'
 awk -v newsums="$newsums" '
 	/^[[:blank:]]*(md|sha)[[:digit:]]+sums(_[^=]+)?=/,/\)[[:blank:]]*(#.*)?$/ {
 		if (!w) {
