Updated msys2

diff --git a/msys2/usr/bin/pacman-key b/msys2/usr/bin/pacman-key
--- a/msys2/usr/bin/pacman-key
+++ b/msys2/usr/bin/pacman-key
@@ -3,7 +3,7 @@
 #   pacman-key - manages pacman's keyring
 #                Based on apt-key, from Debian
 #
-#   Copyright (c) 2010-2021 Pacman Development Team <pacman-dev@archlinux.org>
+#   Copyright (c) 2010-2024 Pacman Development Team <pacman-dev@lists.archlinux.org>
 #
 #   This program is free software; you can redistribute it and/or modify
 #   it under the terms of the GNU General Public License as published by
@@ -23,14 +23,14 @@
 export TEXTDOMAIN='pacman-scripts'
 export TEXTDOMAINDIR='/usr/share/locale'
 
-declare -r myver="6.0.2"
+declare -r myver="6.1.0"
 
-LIBRARY=${LIBRARY:-'/usr/share/makepkg'}
+MAKEPKG_LIBRARY=${MAKEPKG_LIBRARY:-'/usr/share/makepkg'}
 
 # Import libmakepkg
-source "$LIBRARY"/util/message.sh
-source "$LIBRARY"/util/parseopts.sh
-source "$LIBRARY"/utils_fixed_path.sh
+source "$MAKEPKG_LIBRARY"/util/message.sh
+source "$MAKEPKG_LIBRARY"/util/parseopts.sh
+source "$MAKEPKG_LIBRARY"/utils_fixed_path.sh
 
 # Options
 ADD=0
@@ -52,6 +52,9 @@ UPDATEDB=0
 USE_COLOR='y'
 VERIFY=0
 VERBOSE=0
+
+# MSYS2: we don't use WKD, disable it to avoid unnecessary lookup error messages
+_USE_WKD=0
 
 usage() {
 	printf "pacman-key (pacman) %s\n" ${myver}
@@ -85,6 +88,8 @@ usage() {
                             '%s')")\n" "/etc/pacman.conf"
 	printf -- "$(gettext "  --gpgdir <dir>            Set an alternate directory for GnuPG (instead\n\
                             of '%s')")\n" "/etc/pacman.d/gnupg"
+	printf -- "$(gettext "  --populate-from <dir>     Set an alternate directory for --populate (instead\n\
+                            of '%s')")\n" "/usr/share/pacman/keyrings"
 	printf -- "$(gettext "  --keyserver <server-url>  Specify a keyserver to use if necessary")\n"
 	echo
 	printf -- "$(gettext "  -h, --help                Show this help message and exit")\n"
@@ -93,7 +98,7 @@ usage() {
 
 version() {
 	printf "pacman-key (pacman) %s\n" "${myver}"
-	printf -- "Copyright (c) 2010-2021 Pacman Development Team <pacman-dev@archlinux.org>.\n"
+	printf -- "Copyright (c) 2010-2024 Pacman Development Team <pacman-dev@lists.archlinux.org>.\n"
 	printf '\n'
 	printf -- "$(gettext "\
 This is free software; see the source for copying conditions.\n\
@@ -236,7 +241,6 @@ initialize() {
 	chmod 644 "$conffile"
 	add_gpg_conf_option "$conffile" 'no-greeting'
 	add_gpg_conf_option "$conffile" 'no-permission-warning'
-	add_gpg_conf_option "$conffile" 'lock-never'
 	add_gpg_conf_option "$conffile" 'keyserver-options' 'timeout=10'
 	add_gpg_conf_option "$conffile" 'keyserver-options' 'import-clean'
 
@@ -284,7 +288,6 @@ check_keyring() {
 }
 
 populate_keyring() {
-	local KEYRING_IMPORT_DIR='/usr/share/pacman/keyrings'
 
 	local keyring KEYRINGIDS=("$@")
 	local ret=0
@@ -319,7 +322,9 @@ populate_keyring() {
 	# Add keys from requested keyrings
 	for keyring in "${KEYRINGIDS[@]}"; do
 		msg "$(gettext "Appending keys from %s.gpg...")" "$keyring"
-		"${GPG_PACMAN[@]}" --quiet --import "${KEYRING_IMPORT_DIR}/${keyring}.gpg"
+		# FIXME: --allow-weak-key-signatures is a workaround for
+		# https://github.com/msys2/MSYS2-keyring/issues/45
+		"${GPG_PACMAN[@]}" --allow-weak-key-signatures --quiet --import "${KEYRING_IMPORT_DIR}/${keyring}.gpg"
 	done
 
 	# Read the trusted key IDs to an array. Because this is an ownertrust
@@ -379,7 +384,7 @@ populate_keyring() {
 			key_count=$((key_count+1))
 		done
 		if (( key_count )); then
-			msg2 "$(gettext "Disabled %s keys.")" "${key_count}"
+			msg2 "$(ngettext "Disabled %s key." "Disabled %s keys." "${key_count}")" "${key_count}"
 		fi
 	fi
 }
@@ -434,7 +439,7 @@ import_trustdb() {
 	local ret=0
 	for importdir in "$@"; do
 		if [[ -f "${importdir}/trustdb.gpg" ]]; then
-			/bin/gpg --homedir "${importdir}" --export-ownertrust | \
+			/usr/bin/gpg --homedir "${importdir}" --export-ownertrust | \
 				"${GPG_PACMAN[@]}" --import-ownertrust -
 			if (( PIPESTATUS )); then
 				error "$(gettext "%s could not be imported.")" "${importdir}/trustdb.gpg"
@@ -507,7 +512,7 @@ lsign_keys() {
 		exit 1
 	fi
 	if (( key_count )); then
-		msg2 "$(gettext "Locally signed %s keys.")" "${key_count}"
+		msg2 "$(ngettext "Locally signed %s key." "Locally signed %s keys." "${key_count}")" "${key_count}"
 	fi
 }
 
@@ -527,10 +532,15 @@ receive_keys() {
 
 	(( ${#keyids[*]}+${#emails[*]} > 0 )) || exit 1
 
-	if (( ${#emails[*]} > 0 )) && \
+	if (( _USE_WKD )) && (( ${#emails[*]} > 0 )) && \
 	   ! "${GPG_PACMAN[@]}" --auto-key-locate clear,nodefault,wkd,keyserver \
 	                        --locate-key "${emails[@]}" ; then
 		error "$(gettext "Remote key not fetched correctly from WKD or keyserver.")"
+		ret=1
+	elif (( ${#emails[*]} > 0 )) && \
+	   ! "${GPG_PACMAN[@]}" --auto-key-locate clear,nodefault,keyserver \
+	                        --locate-key "${emails[@]}" ; then
+		error "$(gettext "Remote key not fetched correctly from keyserver.")"
 		ret=1
 	fi
 
@@ -562,11 +572,13 @@ refresh_keys() {
 
 		# first try looking up the key in a WKD (only works by email address)
 		for email in "${emails[@]}"; do
-			"${GPG_PACMAN[@]}" --locate-external-keys "$email" && break
+			(( _USE_WKD )) && "${GPG_PACMAN[@]}" --locate-external-keys "$email" && break
 		done
 
 		# if no key was found, fall back to using the keyservers (with the key fingerprint instead)
-		if (( $? )) &&  ! "${GPG_PACMAN[@]}" --refresh-keys "$id"; then
+		# FIXME: --allow-weak-key-signatures is a workaround for
+		# https://github.com/msys2/MSYS2-keyring/issues/45
+		if (( $? )) &&  ! "${GPG_PACMAN[@]}" --allow-weak-key-signatures --refresh-keys "$id"; then
 			error "$(gettext "Could not update key: %s")" "$id"
 			ret=1
 		fi
@@ -591,10 +603,21 @@ verify_sig() {
 		error "$(gettext "Cannot use armored signatures for packages: %s")" "$sig"
 		exit 1
 	fi
-	if ! "${GPG_PACMAN[@]}" --status-fd 1 --verify "${files[@]}" | grep -qE '^\[GNUPG:\] TRUST_(FULLY|ULTIMATE).*$'; then
-		error "$(gettext "The signature identified by %s could not be verified.")" "$sig"
+
+	"${GPG_PACMAN[@]}" --status-fd 1 --verify "${files[@]}" | grep -qE '^\[GNUPG:\] TRUST_(FULLY|ULTIMATE).*$'
+
+	# return error if GnuPG fails to verify the signature
+	if [[ "${PIPESTATUS[0]}" -ne 0 ]]; then
+		error "$(gettext "The signature verification for %s failed.")" "$sig"
 		ret=1
 	fi
+
+	# return error if the signature is not trusted fully or ultimately
+	if [[ "${PIPESTATUS[1]}" -ne 0 ]]; then
+		error "$(gettext "The signature %s is not trusted.")" "$sig"
+		ret=1
+	fi
+
 	exit $ret
 }
 
@@ -617,10 +640,20 @@ else
 	}
 fi
 
+if ! type ngettext &>/dev/null; then
+	ngettext() {
+		if (( $3 == 1 )); then
+			echo "$1"
+		else
+			echo "$2"
+		fi
+	}
+fi
+
 OPT_SHORT="adefhlruvV"
 OPT_LONG=('add' 'config:' 'delete' 'edit-key' 'export' 'finger' 'gpgdir:'
           'help' 'import' 'import-trustdb' 'init' 'keyserver:' 'list-keys' 'list-sigs'
-          'lsign-key' 'nocolor' 'populate' 'recv-keys' 'refresh-keys' 'updatedb'
+          'lsign-key' 'nocolor' 'populate' 'populate-from:' 'recv-keys' 'refresh-keys' 'updatedb'
           'verbose' 'verify' 'version')
 if ! parseopts "$OPT_SHORT" "${OPT_LONG[@]}" -- "$@"; then
 	exit 1 # E_INVALID_OPTION
@@ -642,6 +675,7 @@ while (( $# )); do
 		-e|--export)      EXPORT=1 ;;
 		-f|--finger)      FINGER=1 ;;
 		--gpgdir)         shift; PACMAN_KEYRING_DIR=$1 ;;
+		--populate-from)  shift; KEYRING_IMPORT_DIR=$1 ;;
 		--import)         IMPORT=1 UPDATEDB=1 ;;
 		--import-trustdb) IMPORT_TRUSTDB=1 UPDATEDB=1 ;;
 		--init)           INIT=1 ;;
@@ -682,6 +716,8 @@ if [[ ! -r "${CONFIG}" ]]; then
 	error "$(gettext "%s configuration file '%s' not found.")" "pacman" "$CONFIG"
 	exit 1
 fi
+
+KEYRING_IMPORT_DIR=${KEYRING_IMPORT_DIR:-"/usr/share/pacman/keyrings"}
 
 # if PACMAN_KEYRING_DIR isn't assigned, try to get it from the config
 # file, falling back on a hard default
diff --git a/msys2/usr/bin/repo-add b/msys2/usr/bin/repo-add
--- a/msys2/usr/bin/repo-add
+++ b/msys2/usr/bin/repo-add
@@ -3,7 +3,7 @@
 #   repo-add - add a package to a given repo database file
 #   repo-remove - remove a package entry from a given repo database file
 #
-#   Copyright (c) 2006-2021 Pacman Development Team <pacman-dev@archlinux.org>
+#   Copyright (c) 2006-2024 Pacman Development Team <pacman-dev@lists.archlinux.org>
 #
 #   This program is free software; you can redistribute it and/or modify
 #   it under the terms of the GNU General Public License as published by
@@ -24,10 +24,10 @@ shopt -s extglob
 export TEXTDOMAIN='pacman-scripts'
 export TEXTDOMAINDIR='/usr/share/locale'
 
-declare -r myver='6.0.2'
+declare -r myver='6.1.0'
 declare -r confdir='/etc'
 
-LIBRARY=${LIBRARY:-'/usr/share/makepkg'}
+MAKEPKG_LIBRARY=${MAKEPKG_LIBRARY:-'/usr/share/makepkg'}
 
 QUIET=0
 ONLYADDNEW=0
@@ -42,11 +42,15 @@ LOCKFILE=
 CLEAN_LOCK=0
 USE_COLOR='y'
 PREVENT_DOWNGRADE=0
+INCLUDE_SIGS=0
+DB_MODIFIED=0
+DB_MISSING=0
 
 # Import libmakepkg
-source "$LIBRARY"/util/compress.sh
-source "$LIBRARY"/util/message.sh
-source "$LIBRARY"/utils_fixed_path.sh
+source "$MAKEPKG_LIBRARY"/util/compress.sh
+source "$MAKEPKG_LIBRARY"/util/message.sh
+source "$MAKEPKG_LIBRARY"/util/parseopts.sh
+source "$MAKEPKG_LIBRARY"/utils_fixed_path.sh
 
 # ensure we have a sane umask set
 umask 0022
@@ -97,7 +101,7 @@ See %s(8) for more details and descriptions of the available options.\n")" $cmd
 version() {
 	cmd=${0##*/}
 	printf "%s (pacman) %s\n\n" "$cmd" "$myver"
-	printf -- "Copyright (c) 2006-2021 Pacman Development Team <pacman-dev@archlinux.org>.\n"
+	printf -- "Copyright (c) 2006-2024 Pacman Development Team <pacman-dev@lists.archlinux.org>.\n"
 	printf '\n'
 	printf -- "$(gettext "\
 This is free software; see the source for copying conditions.\n\
@@ -208,7 +212,7 @@ db_write_entry() {
 	local -a _groups _licenses _replaces _depends _conflicts _provides \
 		_optdepends _makedepends _checkdepends
 	local pkgname pkgbase pkgver pkgdesc csize size url arch builddate packager \
-		md5sum sha256sum pgpsig pgpsigsize
+		sha256sum pgpsig pgpsigsize
 
 	# read info from the zipped package
 	local line var val
@@ -261,7 +265,7 @@ db_write_entry() {
 	fi
 
 	# compute base64'd PGP signature
-	if [[ -f "$pkgfile.sig" ]]; then
+	if (( INCLUDE_SIGS )) && [[ -f "$pkgfile.sig" ]]; then
 		if grep -q 'BEGIN PGP SIGNATURE' "$pkgfile.sig"; then
 			error "$(gettext "Cannot use armored signatures for packages: %s")" "$pkgfile.sig"
 			return 1
@@ -279,8 +283,6 @@ db_write_entry() {
 
 	# compute checksums
 	msg2 "$(gettext "Computing checksums...")"
-	md5sum=$(md5sum "$pkgfile")
-	md5sum=${md5sum%% *}
 	sha256sum=$(sha256sum "$pkgfile")
 	sha256sum=${sha256sum%% *}
 
@@ -305,7 +307,6 @@ db_write_entry() {
 		format_entry "ISIZE"     "$size"
 
 		# add checksums
-		format_entry "MD5SUM"    "$md5sum"
 		format_entry "SHA256SUM" "$sha256sum"
 
 		# add PGP sig
@@ -343,6 +344,8 @@ db_write_entry() {
 		rm -f ${oldfile} ${oldfile}.sig
 	fi
 
+	DB_MODIFIED=1
+
 	return 0
 } # end db_write_entry
 
@@ -362,6 +365,8 @@ db_remove_entry() {
 		# remove entries in "files" database
 		local filesentry=$(echo "$pkgentry" | sed 's/\(.*\)\/db\//\1\/files\//')
 		rm -rf "$filesentry"
+
+		DB_MODIFIED=1
 
 		pkgentry=$(find_pkgentry "$pkgname")
 	done
@@ -436,6 +441,8 @@ prepare_repo_db() {
 						exit 1
 					fi
 					rm -f "$dbfile"
+					# mark the db for unconditional update
+					DB_MISSING=1
 					;;
 			esac
 		fi
@@ -590,9 +597,9 @@ if [[ $cmd != "repo-add" && $cmd != "repo-remove" ]]; then
 	exit 1
 fi
 
-tmpdir=$(mktemp -d "${TMPDIR:-/tmp}/repo-tools.XXXXXXXXXX") || (\
-	error "$(gettext "Cannot create temp directory for database building.")"; \
-	exit 1)
+tmpdir=$(mktemp -d "${TMPDIR:-/tmp}/repo-tools.XXXXXXXXXX") || {
+	error "$(gettext "Cannot create temp directory for database building.")";
+	exit 1; }
 
 for repo in "db" "files"; do
 	mkdir "$tmpdir/$repo"
@@ -605,9 +612,19 @@ done
 trap 'trap_exit "$(gettext "Aborted by user! Exiting...")"' INT
 trap 'trap_exit "$(gettext "An unknown error has occurred. Exiting...")"' ERR
 
+
+OPT_SHORT="knpqRsv"
+OPT_LONG=('include-sigs' 'key' 'new' 'nocolor' 'quiet' 'prevent-downgrade' 'remove'
+          'sign' 'verify')
+if ! parseopts "$OPT_SHORT" "${OPT_LONG[@]}" -- "$@"; then
+	exit 1 # E_INVALID_OPTION
+fi
+set -- "${OPTRET[@]}"
+unset OPT_SHORT OPT_LONG OPTRET
+
 declare -a args
 # parse arguments
-while (( $# )); do
+while true; do
 	case $1 in
 		-q|--quiet) QUIET=1;;
 		-n|--new) ONLYADDNEW=1;;
@@ -627,12 +644,18 @@ while (( $# )); do
 		-p|--prevent-downgrade)
 			PREVENT_DOWNGRADE=1
 			;;
-		*)
-			args+=("$1")
+		--include-sigs)
+			INCLUDE_SIGS=1
+			;;
+		--)
+			shift
+			break
 			;;
 	esac
 	shift
 done
+
+args=("$@")
 
 # check if messages are to be printed using color
 if [[ -t 2 && $USE_COLOR != "n" ]]; then
@@ -685,13 +708,17 @@ for arg in "${args[@]:1}"; do
 done
 
 # if the whole operation was a success, re-zip and rotate databases
-if (( !fail )); then
+if (( fail )); then
+	msg "$(gettext "Package database was not modified due to errors.")"
+	exit 1
+fi
+
+if (( DB_MODIFIED || DB_MISSING )); then
 	msg "$(gettext "Creating updated database file '%s'")" "$REPO_DB_FILE"
 	create_db
 	rotate_db
 else
-	msg "$(gettext "No packages modified, nothing to do.")"
-	exit 1
+	msg "$(gettext "No changes made to package database.")"
 fi
 
 exit 0
diff --git a/msys2/usr/bin/xzcmp b/msys2/usr/bin/xzcmp
--- a/msys2/usr/bin/xzcmp
+++ b/msys2/usr/bin/xzcmp
@@ -1,4 +1,5 @@
 #!/bin/sh
+# SPDX-License-Identifier: GPL-2.0-or-later
 
 # Copyright (C) 1998, 2002, 2006, 2007 Free Software Foundation
 # Copyright (C) 1993 Jean-loup Gailly
@@ -15,6 +16,8 @@
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
 
+# shellcheck shell=sh disable=SC1003,SC2016
+
 
 #SET_PATH - This line is a placeholder to ease patching this script.
 
@@ -30,7 +33,7 @@ case ${0##*/} in
   *)     prog=xzdiff; cmp=${DIFF:-diff};;
 esac
 
-version="$prog (XZ Utils) 5.4.3"
+version="$prog (XZ Utils) 5.8.2"
 
 usage="Usage: ${0##*/} [OPTION]... FILE1 [FILE2]
 Compare FILE1 to FILE2, using their uncompressed contents if they are
@@ -62,7 +65,7 @@ done
 cmp="$cmp --"
 
 for file; do
-  test "X$file" = X- || <"$file" || exit 2
+  test "X$file" = X- || true < "$file" || exit 2
 done
 
 # xz needs -qQ to ignore warnings like unsupported check type.
@@ -83,13 +86,17 @@ if test $# -eq 1; then
       xz1=lzop;;
     *[-.]zst | *.tzst)
       xz1='zstd -q';;
+    *[-.]lz4)
+      xz1=lz4;;
     *)
       printf '%s\n' "$0: $1: Unknown compressed file name suffix" >&2
       exit 2;;
   esac
+  # The FILE variable is used with eval, and shellcheck doesn't see that.
+  # shellcheck disable=SC2034
   case $1 in
-    *[-.][zZ] | *_z | *[-.][gx]z | *[-.]bz2 | *[-.]lzma | *[-.]lz | *[-.]lzo | *[-.]zst)
-      FILE=`expr "X$1" : 'X\(.*\)[-.][abglmostxzZ2]*$'`;;
+    *[-.][zZ] | *_z | *[-.][gx]z | *[-.]bz2 | *[-.]lzma | *[-.]lz | *[-.]lzo | *[-.]zst | *[-.]lz4)
+      FILE=`expr "X$1" : 'X\(.*\)[-.][abglmostxzZ24]*$'`;;
     *.t[abglx]z)
       FILE=`expr "X$1" : 'X\(.*[-.]t\)[abglx]z$'`ar;;
     *.tbz2)
@@ -109,17 +116,19 @@ elif test $# -eq 2; then
     *[-.][zZ] | *_z | *[-.]gz | *.t[ag]z) xz1=gzip;;
     *[-.]lzo | *.tzo) xz1=lzop;;
     *[-.]zst | *.tzst) xz1='zstd -q';;
+    *[-.]lz4) xz1=lz4;;
   esac
   case $2 in
     *[-.]bz2 | *.tbz | *.tbz2) xz2=bzip2;;
     *[-.][zZ] | *_z | *[-.]gz | *.t[ag]z) xz2=gzip;;
     *[-.]lzo | *.tzo) xz2=lzop;;
     *[-.]zst | *.tzst) xz2='zstd -q';;
+    *[-.]lz4) xz2=lz4;;
   esac
   case $1 in
-    *[-.][zZ] | *_z | *[-.][gx]z | *[-.]bz2 | *[-.]lzma | *[-.]lz | *.t[abglx]z | *.tbz2 | *[-.]lzo | *.tzo | *[-.]zst | *.tzst | -)
+    *[-.][zZ] | *_z | *[-.][gx]z | *[-.]bz2 | *[-.]lzma | *[-.]lz | *.t[abglx]z | *.tbz2 | *[-.]lzo | *.tzo | *[-.]zst | *.tzst | *[-.]lz4 | -)
       case "$2" in
-        *[-.][zZ] | *_z | *[-.][gx]z | *[-.]bz2 | *[-.]lzma | *[-.]lz | *.t[abglx]z | *.tbz2 | *[-.]lzo | *.tzo | *[-.]zst | *.tzst | -)
+        *[-.][zZ] | *_z | *[-.][gx]z | *[-.]bz2 | *[-.]lzma | *[-.]lz | *.t[abglx]z | *.tbz2 | *[-.]lzo | *.tzo | *[-.]zst | *.tzst | *[-.]lz4 | -)
           if test "$1$2" = --; then
             xz_status=$(
               exec 4>&1
@@ -183,7 +192,7 @@ elif test $# -eq 2; then
     esac;;
   *)
     case "$2" in
-      *[-.][zZ] | *_z | *[-.][gx]z | *[-.]bz2 | *[-.]lzma | *[-.]lz | *.t[abglx]z | *.tbz2 | *[-.]lzo | *.tzo | *[-.]zst | *.tzst | -)
+      *[-.][zZ] | *_z | *[-.][gx]z | *[-.]bz2 | *[-.]lzma | *[-.]lz | *.t[abglx]z | *.tbz2 | *[-.]lzo | *.tzo | *[-.]zst | *.tzst | *[-.]lz4 | -)
         xz_status=$(
           exec 4>&1
           ($xz2 -cdf -- "$2" 4>&-; echo $? >&4) 3>&- |
@@ -194,7 +203,7 @@ elif test $# -eq 2; then
     esac;;
   esac
 else
-  printf '%s\n' "$0: Invalid number of operands; try \`${0##*/} --help' for help" >&2
+  printf '%s\n' "$0: Invalid number of operands; try '${0##*/} --help' for help" >&2
   exit 2
 fi
 
